//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExternalSamplesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExternalSamplesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ExternalSamplesResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indsæt venligst brugernavn og adgangskode for at logge ind.
        /// </summary>
        internal static string ExternalSamplesEnterCredentialsLabel {
            get {
                return ResourceManager.GetString("ExternalSamplesEnterCredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adgangskode.
        /// </summary>
        internal static string ExternalSamplesPasswordLabel {
            get {
                return ResourceManager.GetString("ExternalSamplesPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl for login med &quot;dummy&quot; generisk udbyder.
        /// </summary>
        internal static string ExternalSamplesTitle {
            get {
                return ResourceManager.GetString("ExternalSamplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavn.
        /// </summary>
        internal static string ExternalSamplesUserNameLabel {
            get {
                return ResourceManager.GetString("ExternalSamplesUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du tager adgang til Identify*Portal. Vælg venligst hvilken partner du vil administrere..
        /// </summary>
        internal static string PartnerSelectionTitle {
            get {
                return ResourceManager.GetString("PartnerSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR-nummer opfanger.
        /// </summary>
        internal static string SocialSecurityNumberContent {
            get {
                return ResourceManager.GetString("SocialSecurityNumberContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR-nummer opfanger.
        /// </summary>
        internal static string SocialSecurityNumberHeader {
            get {
                return ResourceManager.GetString("SocialSecurityNumberHeader", resourceCulture);
            }
        }
    }
}
